sh Fr_Az_comp1.sh
sh Fr_Az_comp2.sh
sh Fr_Az_comp3.sh
sh Fr_Az_comp4.sh
sh Fr_Az_comp5.sh
sh Fr_Ir_comp1.sh
sh Fr_Ir_comp2.sh
sh Fr_Ir_comp3.sh
sh Fr_Ir_comp4.sh
sh Fr_Ir_comp5.sh
sh Fr_Mo_comp1.sh
sh Fr_Mo_comp2.sh
sh Fr_Mo_comp3.sh
sh Fr_Mo_comp4.sh
sh Fr_Mo_comp5.sh
sh Fr_ND_comp1.sh
sh Fr_ND_comp2.sh
sh Fr_ND_comp3.sh
sh Fr_ND_comp4.sh
sh Fr_ND_comp5.sh
