---
title: "Ptt_MSMC2"
author: "DT"
date: "2023-02-05"
output: html_document
---
## 1) Variation between runs
```{r echo=FALSE, message=FALSE, warning=FALSE}
setwd("/home/taliadoros/Desktop/phd_projects/Ptt/2022/msmc2/all_chr/RCCR_8_all_1_2_2023/All_rccr/")
library(ggplot2)
library(shiny)
library(plotly)
mu <- 5.7e-9
g <- 1
v0 <- 0.5
read_iter <- function(f,p,pop2) {
  df <- read.table(f, header = T)
  df$Run <- p
  df$Time <- with(df, g * ((right_time_boundary + left_time_boundary) / 2) /mu)
  df$rccr <-  (2 * df$lambda_01)/(df$lambda_00 + df$lambda_11)
  return(df)
}

#Az_Mor
R1 <- read_iter("Az-Mo_1.allrates.txt", "RUN_1")
R2 <- read_iter("Az-Mo_2.allrates.txt", "RUN_2")
R3 <- read_iter("Az-Mo_3.allrates.txt", "RUN_3")
R4 <- read_iter("Az-Mo_4.allrates.txt", "RUN_4")
R5 <- read_iter("Az-Mo_5.allrates.txt", "RUN_5")

Az_Mor_full <- rbind(R1,R2,R3,R4,R5)



p.cross <- ggplot(Az_Mor_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
                    scale_x_log10()+ ylab("RCCR") + xlab("Time") + ggtitle("Azerbaijan Morocco") + theme_minimal()

p.cross


#Az_ND
R1 <- read_iter("Az-ND_1.allrates.txt", "RUN_1")
R2 <- read_iter("Az-ND_2.allrates.txt", "RUN_2")
R3 <- read_iter("Az-ND_3.allrates.txt", "RUN_3")
R4 <- read_iter("Az-ND_4.allrates.txt", "RUN_4")
R5 <- read_iter("Az-ND_5.allrates.txt", "RUN_5")

Az_ND_full <- rbind(R1,R2,R3,R4,R5)

p.cross <- ggplot(Az_ND_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10()+ ylab("RCCR") + xlab("Time") + ggtitle("Azerbaijan USA") + theme_minimal()

p.cross


#Az Fr

R1 <- read_iter("Az-Fr_1.allrates.txt", "RUN_1")
R2 <- read_iter("Az-Fr_2.allrates.txt", "RUN_2")
R3 <- read_iter("Az-Fr_3.allrates.txt", "RUN_3")
R4 <- read_iter("Az-Fr_4.allrates.txt", "RUN_4")
R5 <- read_iter("Az-Fr_5.allrates.txt", "RUN_5")

Az_Fr_full <- rbind(R1,R2,R3,R4,R5)

p.cross <- ggplot(Az_Fr_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10()+ ylab("RCCR") + xlab("Time") + ggtitle("Azerbaijan Europe") + theme_minimal()

p.cross


#AZ IR

R1 <- read_iter("Az-Ir_1.allrates.txt", "RUN_1")
R2 <- read_iter("Az-Ir_2.allrates.txt", "RUN_2")
R3 <- read_iter("Az-Ir_3.allrates.txt", "RUN_3")
R4 <- read_iter("Az-Ir_4.allrates.txt", "RUN_4")
R5 <- read_iter("Az-Ir_5.allrates.txt", "RUN_5")

Az_Ir_full <- rbind(R1,R2,R3,R4,R5)

p.cross <- ggplot(Az_Ir_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Azerbaijan Iran") + theme_minimal()

p.cross


#Mor Fr

R1 <- read_iter("Mo-Fr_1.allrates.txt", "RUN_1")
R2 <- read_iter("Mo-Fr_1.allrates.txt", "RUN_2")
R3 <- read_iter("Mo-Fr_1.allrates.txt", "RUN_3")
R4 <- read_iter("Mo-Fr_1.allrates.txt", "RUN_4")
R5 <- read_iter("Mo-Fr_1.allrates.txt", "RUN_5")

Mor_Fr_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Mor_Fr_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Morocco Europe") + theme_minimal()

p.cross


#Mor Ir

R1 <- read_iter("Mo-Ir_1.allrates.txt", "RUN_1")
R2 <- read_iter("Mo-Ir_1.allrates.txt", "RUN_2")
R3 <- read_iter("Mo-Ir_1.allrates.txt", "RUN_3")
R4 <- read_iter("Mo-Ir_1.allrates.txt", "RUN_4")
R5 <- read_iter("Mo-Ir_1.allrates.txt", "RUN_5")

Mor_Ir_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Mor_Ir_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Morocco Iran") + theme_minimal()

p.cross


#Mor ND 

R1 <- read_iter("Mo-ND_1.allrates.txt", "RUN_1")
R2 <- read_iter("Mo-ND_1.allrates.txt", "RUN_2")
R3 <- read_iter("Mo-ND_1.allrates.txt", "RUN_3")
R4 <- read_iter("Mo-ND_1.allrates.txt", "RUN_4")
R5 <- read_iter("Mo-ND_1.allrates.txt", "RUN_5")

Mor_ND_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Mor_ND_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Morocco USA") + theme_minimal()

p.cross


#Fr Ir

R1 <- read_iter("Fr-Ir_1.allrates.txt", "RUN_1")
R2 <- read_iter("Fr-Ir_2.allrates.txt", "RUN_2")
R3 <- read_iter("Fr-Ir_3.allrates.txt", "RUN_3")
R4 <- read_iter("Fr-Ir_4.allrates.txt", "RUN_4")
R5 <- read_iter("Fr-Ir_5.allrates.txt", "RUN_5")

Fr_Ir_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Fr_Ir_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Europe Iran") + theme_minimal()
p.cross


#Fr ND

R1 <- read_iter("Fr-ND_1.allrates.txt", "RUN_1")
R2 <- read_iter("Fr-ND_2.allrates.txt", "RUN_2")
R3 <- read_iter("Fr-ND_3.allrates.txt", "RUN_3")
R4 <- read_iter("Fr-ND_4.allrates.txt", "RUN_4")
R5 <- read_iter("Fr-ND_5.allrates.txt", "RUN_5")

Fr_ND_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Fr_ND_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Europe USA") + theme_minimal()

p.cross


R1 <- read_iter("Ir-ND_1.allrates.txt", "RUN_1")
R2 <- read_iter("Ir-ND_2.allrates.txt", "RUN_2")
R3 <- read_iter("Ir-ND_3.allrates.txt", "RUN_3")
R4 <- read_iter("Ir-ND_4.allrates.txt", "RUN_4")
R5 <- read_iter("Ir-ND_5.allrates.txt", "RUN_5")

Ir_ND_full <- rbind(R1,R2,R3,R4,R5)


p.cross <- ggplot(Ir_ND_full, aes(x = Time, y=rccr, color = Run)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR") + ggtitle("Iran USA") + theme_minimal()


p.cross
```

## 2) One focal population (hiccups in lines show variation between runs)
```{r echo=FALSE}

Mor_Fr_full["Pop2"] <- "Europe"
Mor_Fr_full["Comp"] <- "Morocco and Europe"
Mor_Ir_full["Pop2"] <- "Iran"
Mor_Ir_full["Comp"] <- "Morocco and Iran"
Mor_ND_full["Pop2"] <- "ND"
Mor_ND_full["Comp"] <- "Morocco and USA"
Az_Mor_full["Pop2"] <- "Azerbaijan"
Az_Mor_full["Comp"] <- "Morocco and Azer"

full_Mor <- rbind(Mor_Fr_full,Mor_Ir_full,Mor_ND_full,Az_Mor_full)

ggplot(full_Mor, aes(x = Time, y=rccr, color = Pop2)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Morocco") + theme_minimal()

Az_Fr_full["Pop2"] <- "Europe"
Az_Ir_full["Pop2"] <- "Iran"
Az_ND_full["Pop2"] <- "USA"
Az_Mor_full["Pop2"] <- "Morocco"


Az_Fr_full["Comp"] <- "Azer + Europe"
Az_Ir_full["Comp"] <- "Azer + Iran"
Az_ND_full["Comp"] <- "Azer + USA"
Az_Mor_full["Comp"] <- "Azer + Morocco"

full_Az <- rbind(Az_Fr_full,Az_Ir_full,Az_ND_full,Az_Mor_full)

ggplot(full_Az, aes(x = Time, y=rccr, color = Pop2)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Azerbaijan") + theme_minimal()


Az_Fr_full["Comp"] <- "Europe + Azerbaijan"
Fr_Ir_full["Comp"] <- "Europe + Iran"
Fr_ND_full["Comp"] <- "Europe + USA"
Mor_Fr_full["Comp"] <- "Europe + Morocco"

Az_Fr_full["Pop2"] <- "Azerbaijan"
Fr_Ir_full["Pop2"] <- "Iran"
Fr_ND_full["Pop2"] <- "USA"
Mor_Fr_full["Pop2"] <- "Morocco"

full_Fr <- rbind(Az_Fr_full,Fr_Ir_full,Fr_ND_full,Mor_Fr_full)

ggplot(full_Fr, aes(x = Time, y=rccr, color = Pop2)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Europe") + theme_minimal()



Az_Ir_full["Pop2"] <- "Azerbaijan"
Ir_ND_full["Pop2"] <- "USA"
Fr_Ir_full["Pop2"] <- "Europe"
Mor_Ir_full["Pop2"] <- "Morocco"


Ir_ND_full["Comp"] <- "Iran + USA"


full_Ir <- rbind(Az_Ir_full,Ir_ND_full,Fr_Ir_full,Mor_Ir_full)

ggplot(full_Ir, aes(x = Time, y=rccr, color = Pop2)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("Iran") + theme_minimal()



Az_ND_full["Pop2"] <- "Azerbaijan"
Ir_ND_full["Pop2"] <- "Iran"
Fr_ND_full["Pop2"] <- "Europe"
Mor_ND_full["Pop2"] <- "Morocco"


full_ND <- rbind(Az_ND_full,Ir_ND_full,Fr_ND_full,Mor_ND_full)

ggplot(full_ND, aes(x = Time, y=rccr, color = Pop2)) + geom_step() +
  scale_x_log10() + xlab("Time") + ylab("RCCR")+ ggtitle("USA") + theme_minimal()

```

## 3) All plots together

```{r echo=FALSE, message=FALSE, warning=FALSE}
full_All <- rbind(Mor_Fr_full,Mor_Ir_full,Mor_ND_full,Az_Mor_full,Az_Fr_full,Az_Ir_full,Az_ND_full,Fr_Ir_full,Fr_ND_full,Ir_ND_full)

pdf("RCCR.pdf")
ggplot(full_All, aes(x = Time, y=rccr, color = Comp)) + geom_smooth() +
  scale_x_continuous(trans = "log10", breaks = c(1e+2,1e+3,1e+4,1e+5)) + xlab("Time") + ylab("RCCR")+ ggtitle("All pops") + theme_bw()

dev.off()
```

```{r echo=FALSE}
#g <- 1
mu <- 5.7e-7
read_demo <- function(f,p) {
  df <- read.table(f, header = T)
  df$Population <- p
  df$Time <- with(df, g * ((right_time_boundary + left_time_boundary) / 2*1000) /mu)
  return(df)
}

demo1 <- read_demo("Iran.msmc.final.txt", p = "Iran")
demo2 <- read_demo("USA.msmc.final.txt", p = "USA")
demo3 <- read_demo("Morocco.msmc.final.txt", p = "Morocco")
demo4 <- read_demo("France.msmc.final.txt", p = "France")
demo5 <- read_demo("Azerbaijan.msmc.final.txt", p = "Azerbaijan")

demo <- rbind(demo1, demo2, demo3, demo4,demo5)
pdf("Ne_all.pdf")
ggplot(demo, aes(x = Time, y= (1/lambda)/(2*mu), color = Population)) + geom_line(aes(col = Population), size = 1) +
  scale_x_continuous(trans = "log10") +annotate("rect", xmin = 6000, xmax = 6000, ymin = 0, ymax = 1e8, fill = gray(1)) +
  geom_line(aes(col = Population), size = 1) +
  scale_x_continuous(trans = "log10", breaks = c(1e+2,1e+3,1e+4,1e+5)) + scale_y_continuous(trans = "log10") + xlab("Time") + ylab("Ne")+ ggtitle("All pops")  + theme_bw()
dev.off()
#p.pop1 <- ggplot(demo, aes(x = Time*1000, y = (1/lambda)/(2*mu))) +
#  annotate("rect", xmin = 6, xmax = 10, ymin = 0, ymax = 1e8, fill = gray(0)) +
#  geom_line(aes(col = Population), size = 1) +
#  scale_x_continuous(trans = "log10",
#                     breaks = c(0.1, 1, 10, 100), 
#                     minor_breaks = c(0.5, 1, 5, 50, 500), 
#                     labels = scales::comma_format(accuracy = 0.1)) +
#  scale_y_log10() + 
#  ylab(expression(Ne)) + xlab("Time (y)") + ggtitle("mu = 4.5e-7)") +
#  scale_color_brewer(type = "qual", palette = 1) +
#  theme_bw() + theme(legend.position = "top", legend.direction = "vertical")
#personal_theme = theme(plot.title = element_text(hjust = 0.5))
#p.pop1

```

